fedidp:
    sigKeyConfig:
        fileName: classpath:cert/fedidp-sig.p12
        keyId: puk_fed_idp_sig
        use: sig
logging:
    level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
        de.gematik: INFO
    file:
        name: logs/application-info.log
server:
    port: 8082

