idp:
  version: @project.version@
  idpSig:
    fileName: classpath:idp_sig.p12
    keyId: puk_idp_sig
    use: sig
  idpEnc:
    fileName: classpath:idp_enc.p12
    keyId: puk_idp_enc
    use: enc
  discSig:
    fileName: classpath:disc_sig.p12
    keyId: puk_disc_sig
  symmetricEncryptionKey: "geheimerSchluesselDerNochGehashtWird"
  defaultLocale: US
  debug:
    requestLogging: true
  subjectSaltValue: fkdlsjaviaen4evdsnavaew4vcxo
  blockedClientSystems:
    - "blocked_user_agent"
  userConsent:
    descriptionTexts:
      scopes:
        OPENID: "Zugriff auf den ID-Token."
        EREZEPT: "Zugriff auf die E-Rezept-Funktionalität."
        PAIRING: "Zugriff auf die Daten für die biometrischer Authentisierung."
      claims:
        GIVEN_NAME: "Zustimmung zur Verarbeitung des Vornamens"
        PROFESSION_OID: "Zustimmung zur Verarbeitung der Rolle"
        ORGANIZATION_NAME: "Zustimmung zur Verarbeitung der Organisationszugehörigkeit"
        FAMILY_NAME: "Zustimmung zur Verarbeitung des Nachnamens"
        ID_NUMBER: "Zustimmung zur Verarbeitung der Id (z.B. Krankenversichertennummer, Telematik-Id)"
    claimsToBeIncluded:
      EREZEPT: [ GIVEN_NAME, FAMILY_NAME, ORGANIZATION_NAME, PROFESSION_OID, ID_NUMBER ]
      PAIRING: [ ID_NUMBER ]
  productTypeDisplayString: "IDP"
  scopeAudienceUrls:
    e-rezept: "https://erp-test.zentral.erp.splitdns.ti-dienste.de/"
    pairing: "https://idp-pairing-test.zentral.idp.splitdns.ti-dienste.de"
  registeredClient:
    eRezeptApp:
      redirectUri: http://redirect.gematik.de/erezept
      returnSsoToken: true
    gematikTestPs:
      redirectUri: http://test-ps.gematik.de/erezept
      returnSsoToken: false
  errors:
    genericErrorMap:
      client_id:
        detailMessage: "client_id wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 1002
      redirect_uri:
        detailMessage: "redirect_uri wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 1004
      scope:
        detailMessage: "scope wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 1005
        httpStatusCode: 302
      state:
        detailMessage: "state wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 2002
        httpStatusCode: 302
      response_type:
        detailMessage: "response_type wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 2004
        httpStatusCode: 302
      code_challenge_method:
        detailMessage: "code_challenge_method wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 2008
        httpStatusCode: 302
      code_challenge:
        detailMessage: "code_challenge wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 2009
        httpStatusCode: 302
      key_verifier:
        detailMessage: "key_verifier wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 3004
      code:
        detailMessage: "Authorization Code wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 3005
      grant_type:
        detailMessage: "grant_type wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 3006
    errorCodeMap:
      1002:
        detailMessage: "client_id wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 1002
      1004:
        detailMessage: "redirect_uri wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 1004
      1020:
        detailMessage: "redirect_uri ist ungültig"
        error: INVALID_REQUEST
        code: 1020
      2002:
        detailMessage: "state wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 2002
        httpStatusCode: 302
      2004:
        detailMessage: "response_type wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 2004
        httpStatusCode: 302
      2005:
        detailMessage: "response_type wird nicht unterstützt"
        error: UNSUPPORTED_RESPONSE_TYPE
        code: 2005
        httpStatusCode: 302
      2006:
        detailMessage: "state ist ungültig"
        error: INVALID_REQUEST
        code: 2006
        httpStatusCode: 302
      2007:
        detailMessage: "nonce ist ungültig"
        error: INVALID_REQUEST
        code: 2007
      2008:
        detailMessage: "code_challenge_method ist ungültig"
        error: INVALID_REQUEST
        code: 2008
        httpStatusCode: 302
      2009:
        detailMessage: "code_challenge wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 2009
        httpStatusCode: 302
      2010:
        detailMessage: "code_challenge ist ungültig"
        error: INVALID_REQUEST
        code: 2010
        httpStatusCode: 302
      2012:
        detailMessage: "client_id ist ungültig"
        error: INVALID_REQUEST
        code: 2012
      2013:
        detailMessage: "Der Request besitzt keine gültige Signatur"
        error: INVALID_REQUEST
        code: 2013
      2020:
        detailMessage: "Das AUT Zertifikat ist ungültig"
        error: INVALID_REQUEST
        code: 2020
      2030:
        detailMessage: "Challenge ist ungültig"
        error: INVALID_REQUEST
        code: 2030
      2032:
        detailMessage: "Challenge ist abgelaufen"
        error: INVALID_REQUEST
        code: 2032
      2040:
        detailMessage: "SSO_TOKEN nicht valide, bitte um neuerliche Authentisierung"
        error: ACCESS_DENIED
        code: 2040
      3006:
        detailMessage: "grant_type wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 3006
      3007:
        detailMessage: "client_id ist ungültig"
        error: INVALID_CLIENT
        code: 3007
      3014:
        detailMessage: "grant_type wird nicht unterstützt"
        error: UNSUPPORTED_GRANT_TYPE
        code: 3014
      4000:
        detailMessage: "Der Auftrag zur Deaktivierung des Pairings konnte nicht angenommen werden."
        error: INVALID_REQUEST
        code: 4000
      4001:
        detailMessage: "key_identifier wurde nicht übermittelt"
        error: INVALID_REQUEST
        code: 4001
    joseExceptionMap:
      ChallengeSignatureInvalidException:
        detailMessage: "Der Request besitzt keine gültige Signatur"
        error: INVALID_REQUEST
        code: 2013
      NoNestedJwtFoundException:
        detailMessage: "Challenge ist ungültig"
        error: INVALID_REQUEST
        code: 2030
      ChallengeExpiredException:
        detailMessage: "Challenge ist abgelaufen"
        error: INVALID_REQUEST
        code: 2032

caching:
  discoveryDocument:
    cacheControl: "max-age=300"
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    de.gematik: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    httptrace:
      enabled: true
spring:
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/idp-changelog-master.xml"
  datasource:
    url: "jdbc:h2:mem:idp;INIT=CREATE SCHEMA IF NOT EXISTS IDP;"
    driver-class-name: org.h2.Driver
    username: root
    password: idp
    liquibaseSchemaName: IDP
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
